spring:
  application:
    name: statemachine-sample
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
#    hibernate:
#      use-new-id-generator-mappings: true
#  data:
#    rest:
#      enable-enum-translation: true

logging:
  level:
    root: 'INFO'
    org.hibernate.SQL: DEBUG
